### ISSUE TITLE
error spam

### ISSUE THREAD

**Issue by jackghe** [Emana202/L4D2-Survivor-Bot-AI-Improver#28]
This error keep post up when playing with left 4 bots 2 enable. I use latest version on github

InputRunScript line = (1) column = (127) : error unfinished string

AN ERROR HAS OCCURED [the index 'Curr' does not exist]

CALLSTACK
*FUNCTION [main()] InputRunScript line [1]

LOCALS
[scope] TABLE
[ply] INSTANCE
[vargv] ARRAY
[this] TABLE
Coach's L4B2 Stuff: MoveType = 0	OrderType = ``
Update:This error have very rare chance to nuke server when transition to next chapter
there is crashlog: [crashlog.txt](https://github.com/user-attachments/files/21333597/crashlog.txt)
If am wrong please tell me.

**Comment by Emana202** [comment]
Should be resolved now in the commit. Don't forget to update the gamedata as well.

**Comment by jackghe** [comment]
Error is still here
Error look like cause by line 3393 --> 3398
sorry i really don't know how to use github effective
